# Workspace members
[workspace]
members = [ "custom_array", "huffman",
    "shannon"
]
resolver = "2"

[workspace.dependencies]

# Common dependencies
#tokio = { version = "1", features = ["full"] }
#anyhow = "1"
